from pathlib import Path
from pydantic import Field

from cowork.common.settings import Settings


class AntonHarnessSettings(Settings):
    publish_url: str = Field(
        default="https://4nton.ai",
        description="The URL to publish artifacts generated by the Anton harness",
        validation_alias="ANTON_PUBLISH_URL",
    )  # ANTON_PUBLISH_URL
    publish_ssl_verify: bool = Field(
        default=True,
        description="Whether to verify SSL certificates when publishing artifacts to the publish URL",
        validation_alias="ANTON_SSL_VERIFY",
    )  # ANTON_SSL_VERIFY
    # Skills are global, they are not scoped to any particular project.
    skills_root_dir: str = Field(
        default=str(Path.home() / ".cowork" / "anton" / "skills"),
        description="The root directory where the Anton harness will store skill-related files",
        validation_alias="ANTON_SKILLS_ROOT_DIR",
    )  # ANTON_SKILLS_ROOT_DIR
    # This is for memory scoped at the global level.
    # Project specific memory will be stored in the relevant project dir.
    global_memory_root_dir: str = Field(
        default=str(Path.home() / ".cowork" / "anton" / "memory"),
        description="The root directory where the Anton harness will store memory files for global scope",
        validation_alias="ANTON_GLOBAL_MEMORY_ROOT_DIR",
    )  # ANTON_GLOBAL_MEMORY_ROOT_DIR