from pydantic import Field

from cowork.common.paths import cowork_home
from cowork.common.settings import Settings
from cowork.common.settings.app_settings import default_publish_url


class AntonHarnessSettings(Settings):
    publish_url: str = Field(
        default_factory=default_publish_url,
        description="The URL to publish artifacts generated by the Anton harness",
        validation_alias="ANTON_PUBLISH_URL",
    )  # ANTON_PUBLISH_URL
    publish_ssl_verify: bool = Field(
        default=True,
        description="Whether to verify SSL certificates when publishing artifacts to the publish URL",
        validation_alias="ANTON_SSL_VERIFY",
    )  # ANTON_SSL_VERIFY
    # Skills are global, they are not scoped to any particular project.
    skills_root_dir: str = Field(
        default_factory=lambda: str(cowork_home() / "anton" / "skills"),
        description="The root directory where the Anton harness will store skill-related files",
        validation_alias="ANTON_SKILLS_ROOT_DIR",
    )  # ANTON_SKILLS_ROOT_DIR
