name: Dev - Build and Deploy on PR

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

permissions:
  contents: read

defaults:
  run:
    shell: bash

# Cancel any existing runs of this workflow on the same branch/pr
# We always want to build/deploy/test a new commit over an older one
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:

  run-unit-tests:
    # Runs unit tests
    uses: ./.github/workflows/tests-unit.yml


  build:
    runs-on: mdb-dev
    outputs:
      image: ${{ steps.build.outputs.image }}
    env:
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4
      - uses: mindsdb/github-actions/setup-env@main
      - id: build
        uses: mindsdb/github-actions/build-push-ecr@main
        with:
          module-name: ${{ env.CI_REPOSITORY_SLUG }}
          build-for-environment: development


  scan:
    runs-on: mdb-dev
    needs: [build]
    name: Scan Minds Image
    steps:
      - uses: actions/checkout@v4
      - uses: mindsdb/github-actions/snyk-docker-scan@main
        with:
          image: ${{ needs.build.outputs.image }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}


  deploy-pr-env:
    runs-on: mdb-dev
    needs: [build]
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    environment:
      name: pr-cowork-server-${{ github.event.pull_request.number }}
      url: https://pr-cowork-server-${{ github.event.pull_request.number }}.dev.mindshub.ai
    steps:
      - uses: mindsdb/github-actions/argocd-pr-env-deploy@main
        with:
          argocd-token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          gh-token:     ${{ secrets.GH_PULL_REQUEST_READ_TOKEN }}